import Head from 'next/head'
import { Inter } from 'next/font/google'
import { InferGetStaticPropsType } from 'next'
import axios from 'axios'
import Link from 'next/link'
import Image from 'next/image'
import { Toaster, toast } from "react-hot-toast"
import { useState } from 'react'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  try {
    const { data } = await axios.get("https://retoolapi.dev/2b2Pf9/data")
  
    return {
      props: { blogs: data }
    }
  }
  catch {(error: any) => {
    console.log(error)
  }
  }
}

export default function Home({blogs}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(blogs)
  const router = useRouter()
  
  return (
    <>
      <Head>
        <title>Blog | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div><Toaster position="bottom-right"/></div>

      <div className="px-24 py-16">
      {blogs.map((blog: any) => (
          <div className="bg-[#F2F2F2] w-2/6 p-12 relative rounded-md hover:shadow-lg my-12" key={blog.id}>
            <Image className='absolute right-8 top-8 hover:opacity-70 cursor-pointer' src="/exit-icon.png" alt='Exit' title='Delete blog' width={32} height={32} onClick={async () => {
             await axios.delete("https://retoolapi.dev/2b2Pf9/data/" + blog.id)
              .then((response) => {
                console.log(response)
                toast.success("Blog successfully removed!")
                router.replace(router.asPath)
              })
              .catch((error) => {
                console.log(error)
                toast.error("Failed to delete blog!")
              })
            }} ></Image>
            <h1 className=" text-4xl pb-1.5 font-bold overflow-hidden text-ellipsis whitespace-nowrap">{blog.title}</h1>
            <p className=" max-w-[35ch] pt-6 text-justify text-lg text-limit">{blog.body}</p>
          <Link href={"/" + blog.id} > <button className="absolute px-10 py-2 bottom-5 right-8 bg-[#445045] text-white font-semibold rounded-lg hover:opacity-90">Read more</button> </Link>
          </div>
      ))}
      </div>

    </>
  )
}
